name: fhir
description: FHIR R4, STU3 and DSTU2 for Dart & Flutter.
version: 0.0.1
author: Grey Faulkenberry
homepage: https://sites.google.com/view/hswtllc/home

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  dartz: ^0.9.1
  string_validator: ^0.1.4
  freezed_annotation: ^0.11.0
  sembast: ^2.4.5
  sembast_sqflite: ^0.2.0+2
  path: ^1.7.0
  equatable: ^1.2.0
  bloc: ^4.0.0

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.8.1
  freezed: ^0.11.0